name: .NET5 R4

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./src/R4
      run: dotnet restore
    - name: Build R4
      working-directory: ./src/R4
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src/R4
      run: dotnet test --no-restore --verbosity normal
