name: .NET STU3 pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      working-directory: ./src/STU3
      run: dotnet restore
    - name: Build
      working-directory: ./src/STU3
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src/STU3
      run: dotnet test --no-restore --verbosity normal
